@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-down-> "1" UniqueEventList

UniquePersonList -right-> Person
UniqueEventList -down-> Event

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Year
Person *--> Role
Event *--> EventName
Event *--> Date
Event *--> Venue

@enduml
